# Site metadata
site_name: uaRO Documentation
site_description: The official documentation for uaRO World of your Dream
site_author: uaRO Team
site_url: https://wiki.uaro.net

# Theme configuration
theme:
  logo: img/logo.png
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: lime
      media: "(prefers-color-scheme: dark)"

# Navigation setup
nav:
  - Home: index.md

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
      permalink_title: "Anchor link to this section"
      toc_depth: 3
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      auto_title: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - search
  - mike

# Extra configurations
extra:
  logo: img/logo.png
  favicon: img/favicon.ico
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/uaro-the-world-of-your-dream-702960460168953946
      name: Discord
  footer:
    text: "© 2023-2024 World of Your Dream"
  hide:
    - toc: ["index.md"]

# Custom CSS and JS
extra_css:
  - stylesheets/custom.css
extra_javascript:
  - javascripts/custom.js

# Deployment Fix: Avoid "site" duplication
site_dir: "/var/www/wiki.uaro.net/public_html"
