# Site metadata
site_name: uaRO Documentation
site_description: The official documentation for uaRO World of your Dream
site_author: uaRO Team
site_url: https://wiki.uaro.net

# Theme configuration
theme:
  logo: img/logo.png
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: blue

# Navigation setup
nav: 
  - 👋 Welcome to uaRO: index.md
  - ℹ️ Server Information: Server_Info.md
  - 📖 Server Rules: Server_Rules.md 
  - 🌳 Donations: Donations.md 
  - 🧵 Patch Notes: All_Patch_Notes.md 
  - 🚀 Download uaRO ↗: https://www.uaro.net/cp/?module=service&action=downloads
  - 👾 Join us on Discord ↗: https://discord.gg/uaro-the-world-of-your-dream-702960460168953946
  - Getting Started: 
    - ⭐ How to start: How_To_Start.md 
    - ⚙️ Commands: Commands.md
    - 🌱 Beginner Guide: Beginner_Guide.md 
    - 🔮 Class Changes: Class_Changes.md
    - 🦋 QOL Improvements: Improvements.md
    - 💤 Adventurer Inns: Inns.md
    - 🍬 Convenient Dealers: Dealers.md
    - 🛟 Troubleshooting: Troubleshooting.md
    - 💬 FAQ: FAQ.md
  - Key Features:
    - 🏡 Main Office: Main_Office.md
    - 🐱 Cute Pet System: Pet_System.md
    - ⚔️ Hunting Missions: Hunting_Mission.md
    - 💖 Poring Coin System: Poring_Coins_System.md
    - 🎉 Repeatable Quests: Repeatable_Quests.md 
    - 💰 Vendor System: Vendor_System.md
    - 🌀 Warper System: Warper_System.md
  - Enhancements: 
    - 🔔 Attendance Rewards: Attendance_System.md
    - 🎟️ Card Exchange: Card_Exchange.md 
    - 🧚 Custom NPCs: Custom_NPC.md
    - 🎭 Costume Converter: Costume_Converter.md
    - 👒 Headgear Quests: Dimonka_Headgear_Quest.md 
    - 🕥 Hourly Rewards: Hourly_Rewards_System.md 
    - 🔪 Mercenary System: Mercenary_System.md 
    - 💎 Modified Sales Prices: Modified_Sales_Prices.md 
    - 🗺️ Navigation System: Navigation_System.md 
    - 🐣 Remastered Novice Grounds: Remastered_Novice_Location.md 
  - Dungeons: 
    - 🧪 Biolabs 4: Biolab4.md 
    - ⏳ Endless Cellar: Endless_Cellar.md 
    # - Endless Tower: Endless_Tower.md 
    - 🎁 Horror Toy Factory: Horror_Toy_Factory.md 
    - 👻 Old Glast Heim: Old_Glast_Heim.md 
  - Events & Activites:
    - 🍀 Auto Events: Auto_Events.md 
    - 🎲 Lottery: Lottery_NPC.md 
    - 🐎 Hugel Mini Games: Hugel_Mini_Game.md
    - 🏰 War of Emperium: WoE.md
    - 🏯 Pre-Trans WoE: Pre_Trans_WoE.md
  
# Markdown extensions
markdown_extensions:
  # Table of contents with anchor links
  - toc:
      permalink: true
      permalink_title: "Anchor link to this section"
      toc_depth: 2

  # Abbreviations
  - abbr

  # Admonitions (callout boxes like "note", "warning")
  - admonition

  # Custom HTML attributes and CSS for elements
  - attr_list

  # Definition lists (description lists)
  - def_list

  # Footnotes
  - footnotes

  # Markdown inside HTML
  - md_in_html

  # Tables in Markdown
  - tables

  # Task lists with checkboxes (for to-do lists)
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false

  # Advanced fenced code blocks
  - pymdownx.superfences

  # Syntax highlighting for code blocks
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true

  # Inline code highlighting
  - pymdownx.inlinehilite

  # Better emphasis for bold and italic
  - pymdownx.betterem

  # Highlighting for caret (^), mark (~), and tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # Critic markup for tracking changes
  - pymdownx.critic:
      mode: view

  # Collapsible sections
  - pymdownx.details

  # Emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Arithmatex for mathematical typesetting
  - pymdownx.arithmatex:
      generic: true

  # Support for content tabs
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - search  # Built-in search functionality for MkDocs

# Extra configurations (logo, favicon, social links, analytics)
extra:
  logo: img/logo.png  # Your custom logo
  favicon: img/favicon.ico
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/uaro-the-world-of-your-dream-702960460168953946
      name: uaRO Discord
    - icon: fontawesome/solid/globe
      link: https://www.uaro.net/
      name: uaRO Website
    - icon: fontawesome/solid/download
      link: https://www.uaro.net/cp/?module=service&action=downloads
      name: Download uaRO

# Google Analytics tracking
  analytics:
    provider: google
    property: G-7XD6KF8G73

extra_css:
  - css/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/tablesort.js

copyright: © 2023-2025 World of Your Dream / uaRO 